import { PropsWithChildren } from 'react';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Toaster } from 'sonner';

import Background from '@/core/components/layouts/background';
import Header from '@/core/components/layouts/header';
import Providers from '@/core/components/providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Terry Henrard Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${geistMono.variable} min-h-screen pt-16 antialiased`}
      >
        <Providers>
          <Header />
          <Background />
          {children}
          <Toaster position='top-center' />
        </Providers>
      </body>
    </html>
  );
}
